---
- name: Configure ceilometer-compute server
  hosts: nova-compute
  sudo: True
  gather_facts: True
  vars:
    component: ceilometer
    subcomponent: compute
    packages:
      - "openstack-{{ component }}-{{ subcomponent }}"
    services:
      - "openstack-{{ component }}-{{ subcomponent }}"
    config_files:
      - "{{ component }}.conf"

  tasks:

    - name: ensure {{ component }}-{{ subcomponent }} packages are installed
      yum: 
        pkg: "{{ item }}"
        state: latest 
         
        
      with_items: packages

    - name: ensure services are stopped
      service: 
        name: "{{ item }}"
        state: stopped
      with_items: services

    - name: ensure {{ component }} sqlite is deleted
      file: 
        dest: /var/lib/{{ component }}/{{ component }}.sqlite 
        state: absent

    - name: update configuration files from templates
      template: 
        src: templates/etc/{{ component }}/{{ item }}
        dest: /etc/{{ component }}/{{ item }}
        owner: "{{ component }}"
        group: "{{ component }}"
        mode: 0600
      with_items: config_files

    - name: ensure services are started and enabled
      service: 
        name: "{{ item }}"
        state: restarted 
        enabled: yes
      with_items: services
