---
- name: gather needed facts for template
  hosts: mysql:rabbitmq:keystone:glance:neutron-api:nova-controller

- name: Install nova compute on nodes
  hosts: nova-compute
  sudo: True
  gather_facts: True
  tasks:

    - name: ensure /boot/vmlinuz is world-readable
      shell: chmod 0644 /boot/vmlinuz*

    - name: ensure nova-compute packages are installed
      yum: 
        pkg: "{{ item }}"
        state: latest 
         
        
      with_items:
        - "openstack-nova-compute"
        - python-libguestfs
      
    - name: ensure services are stopped
      service: 
        name: openstack-nova-compute 
        state: stopped

    - name: ensure nova.conf file is present
      template: 
        src: templates/etc/nova/nova.conf 
        dest: /etc/nova/nova.conf 
        owner: nova 
        group: nova 
        mode: 0600

    - name: update api-paste.ini from template
      template: 
        src: templates/etc/nova/api-paste.ini 
        dest: /etc/nova/api-paste.ini 
        owner: nova 
        group: nova 
        mode: 0600

    - name: ensure compute service is started and enabled
      service: 
        name: openstack-nova-compute 
        state: restarted 
        enabled: yes

