---
- name: setup steps that are not specific to a particular role or project
  hosts: all
  sudo: True
  gather_facts: True
  tasks:
    - name: Downloading and enable the EPEL repository definitions.
      action: command rpm -Uvh --replacepkgs http://dl.fedoraproject.org/pub/epel/6/x86_64/epel-release-6-8.noarch.rpm

    - name: Downloading and enable the CERN repository definitions (PYTHON 2.7)
      action: command wget http://linuxsoft.cern.ch/cern/scl/slc6-scl.repo --output-document=/etc/yum.repos.d/slc6-scl.repo

    - name: Enable havana repositorie
      yum: 
        name: http://repos.fedorapeople.org/repos/openstack/openstack-havana/rdo-release-havana-7.noarch.rpm 
        state: present

    - name: update yum cache
      yum: 
        name=* state=latest

    - name: ensure required base packages are present
      yum: 
        pkg: "{{ item }}" 
        state: latest 

      with_items:
        - openstack-selinux
        - chrony
        - MySQL-python
        - openstack-utils
        - rsync


    - name: upgrade software packages to latest version
      yum: name=* state=latest


    - name: register running kernel version
      command: uname -r
      register: running_kernel

    - name: register installed kernel version
      shell: dpkg -l | grep "linux-image-[0-9]" | sort | tail -1 | perl -ane 'print substr($F[1], 12), "\n"'
      register: installed_kernel

#    - name: reboot if kernel version has changed
#      include: reboot.yaml
#      when: installed_kernel.stdout != running_kernel.stdout

    - name: ensure chrony server is stopped
      service: 
        name: chronyd
        state: stopped

    - name: install chrony.conf 
      template: 
        src: templates/etc/chrony/chrony.conf 
        dest: /etc/chrony.conf 
        owner: root 
        group: root 
        mode: 0644

    - name: set clocks to public ntp server
      command: ntpdate {{ external_ntp_host }}
      ignore_errors: yes

    # register: ntpdate_result
    # until: ntpdate_result|success
    # retries: 5
    # delay: 5

    #- name: make sure chrony server is started and enabled
    #  service: 
    #    name: chrony
    #    state: restarted 
    #    enabled: yes
    #  when: "'ntpserver' in group_names"

    #- name: set clocks to local chrony server
    #  command: ntpdate {{ ntp_host }}
    #  register: ntpdate_result
    #  when: "'ntpserver' not in group_names"
    #  until: ntpdate_result|success
    #  retries: 5
    #  delay: 5

    - name: save system clock to hardware
      command: hwclock --systohc

    - name: make sure chrony is started and enabled everywhere
      service: 
        name: chronyd
        state: restarted 
        enabled: yes

- include: virtualbox.yaml
  when: ansible_virtualization_type|defined and ansible_virtualization_type == "virtualbox"
